### ISSUE TITLE
As you don't have discussions enabled ..

### ISSUE THREAD

**Issue by gavanderhoorn** [stefanbesler/struckig#1]
.. I opened this issue.

Not because there is an issue, but just to let you know this is an awesome effort.

Thanks for making that effort :+1:

**Comment by gavanderhoorn** [comment]
Oh, and:

> If you are looking for best possible performance of Ruckig, I suggest you look into making pantor/ruckig a TwinCAT C++ module.

I was indeed going to suggest looking into that.

Not necessarily because of performance, but because it might be easier/more efficient.

That's probably because I haven't tried yet, so it's very much possible I'm wrong.

**Comment by stefanbesler** [comment]
@gavanderhoorn from my experience with C++ modules in Twincat I think that this might actually pretty easy to do. Beckhoff brings its own standard library implementation. Most libraries I wanted to make available in TwinCAT were pretty hard to get working. I once tried to get Eigen working and actually got pretty far, but on some point I just gave up. Ruckig will probably work directly when using C++11 instead of C++17. 

I don't really like that signing mechanics of C++ modules and as far as I know this is still needed (Beckhoff promised to get rid of this in the future?). 
Also, I would really like to know how well the codesys compiler does with this code. I guess it will be one order of magnitude slower, but I would really like to have this kind of functionality directly in TwinCAT without the need of proprietary libraries.
